#ifndef MODEL_H
#define MODEL_H

// This file should contain the C-byte array generated by `xxd` or similar tools
// from your trained .tflite model.

// Example:
// unsigned char g_model[] = { 0x1c, 0x00, ... };
// unsigned int g_model_len = 1234;

// ⚠️ REPLACE THE CONTENT BELOW WITH YOUR HEX DUMP ⚠️

extern const unsigned char g_model[];
extern const unsigned int g_model_len;

// Placeholder implementation to allow compilation of the sketch before real data is inserted
#ifdef __cplusplus
extern "C" {
#endif

// Dummy data
const unsigned char g_model[] __attribute__((aligned(16))) = {
    0x00, 0x00, 0x00, 0x00 // Invalid FLatBuffer, just for template
};
const unsigned int g_model_len = 4;

#ifdef __cplusplus
}
#endif

#endif // MODEL_H
